# This test should fail with status code 1

name: ci


on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: tests
    runs-on: Ubuntu 22.04.2 LTS

    steps: 
      - name: Set up Go
        uses: actions/setup-go@v4
        with: 
        go-version: "1.20"


      - name: Check out code
        uses: actions/checkout@v3

      - name: Force Failure
        run: (exit 1) 
