name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Dockerhub credentials
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: scripts/buildprod.sh

      - name: Logint to Dockerhub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Deploy to dockerhub
        run: scripts/deploy.sh
