name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: scripts/buildprod.sh

      - name: Deploy to dockerhub
        run: scripts/deploy.sh
