name: cd

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build production
        run: ./scripts/buildprod.sh