name: ci

on:
  pull_request:
    branches: [main]

jobs:
<<<<<<< Updated upstream
  tests:
    name: tests
=======
  test:
    name: Tests
>>>>>>> Stashed changes
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Check out code
        uses: actions/checkout@v3

<<<<<<< Updated upstream
      - name: Echo Go Version
        run: go version

      - name: Run go tests
        run: go test ./...

      - name: Run go tests with -cover
        run: go test -cover ./...
=======
      - name: Run test
        run: go test -cover ./...

  style:
    name: format
    runs-on: ubuntu-latest

    steps:
      - name: set-up go
        uses: actions/setup@v4
        with:
          go-version: "1.20"

      - name: checkout code
        uses: actions/checkout@v3

      - name: run format
        run: go fmt ./...
>>>>>>> Stashed changes
