name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          
      - name: Check out code
        uses: actions/checkout@v3

      - name: Execute go version
        run: go version

      - name: Run unit tests 
        run: go test -cover ./...

  style:
    name: check fmt'ing
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          
      - name: Check out code
        uses: actions/checkout@v3

      - name: check go fmt
        run: test -z $(go fmt ./...)

      - name: install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      
      - name: lint
        run: staticcheck ./...


